"""add centre slots and confirmed booking references

Revision ID: b81a9f3e4c21
Revises: 4f4f7a08c9a9
Create Date: 2026-09-20 10:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81a9f3e4c21'
down_revision: Union[str, None] = '4f4f7a08c9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'centre_slots',
        sa.Column('id', sa.Uuid(), nullable=False, comment='Authoritative centre slot UUID'),
        sa.Column('centre_id', sa.Uuid(), nullable=False, comment='Procurement centre UUID'),
        sa.Column('capacity_id', sa.Uuid(), nullable=False, comment='Parent daily capacity UUID'),
        sa.Column('slot_date', sa.Date(), nullable=False, comment='Slot calendar date'),
        sa.Column('start_time', sa.Time(), nullable=False, comment='Slot start time'),
        sa.Column('end_time', sa.Time(), nullable=False, comment='Slot end time'),
        sa.Column('quantity_capacity', sa.Numeric(precision=12, scale=3), nullable=False, comment='Quantity capacity in quintals'),
        sa.Column('booked_quantity', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False, comment='Booked quantity in quintals'),
        sa.Column('max_bookings', sa.Integer(), server_default='20', nullable=False, comment='Maximum allowed bookings in this slot'),
        sa.Column('booked_bookings', sa.Integer(), server_default='0', nullable=False, comment='Current number of confirmed bookings'),
        sa.Column('status', sa.String(length=32), server_default='AVAILABLE', nullable=False, comment='Current slot status (AVAILABLE, FULL, PAUSED, CLOSED)'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
        sa.ForeignKeyConstraint(['capacity_id'], ['centre_capacity.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['centre_id'], ['procurement_centres.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('centre_id', 'slot_date', 'start_time', 'end_time', name='uq_centre_slot_window'),
        sa.CheckConstraint('start_time < end_time', name='ck_centre_slot_time_order'),
        sa.CheckConstraint('quantity_capacity > 0', name='ck_centre_slot_quantity_capacity'),
        sa.CheckConstraint('booked_quantity >= 0 AND booked_quantity <= quantity_capacity', name='ck_centre_slot_booked_quantity'),
        sa.CheckConstraint('max_bookings > 0', name='ck_centre_slot_max_bookings'),
        sa.CheckConstraint('booked_bookings >= 0 AND booked_bookings <= max_bookings', name='ck_centre_slot_booked_bookings'),
    )
    op.create_index(op.f('ix_centre_slots_capacity_id'), 'centre_slots', ['capacity_id'], unique=False)
    op.create_index(op.f('ix_centre_slots_centre_id'), 'centre_slots', ['centre_id'], unique=False)
    op.create_index(op.f('ix_centre_slots_slot_date'), 'centre_slots', ['slot_date'], unique=False)
    op.create_index(op.f('ix_centre_slots_status'), 'centre_slots', ['status'], unique=False)

    op.add_column('procurement_requests', sa.Column('confirmed_centre_id', sa.Uuid(), nullable=True, comment='Procurement centre confirmed for booking'))
    op.add_column('procurement_requests', sa.Column('confirmed_slot_id', sa.Uuid(), nullable=True, comment='Slot confirmed for booking'))
    op.create_index(op.f('ix_procurement_requests_confirmed_centre_id'), 'procurement_requests', ['confirmed_centre_id'], unique=False)
    op.create_index(op.f('ix_procurement_requests_confirmed_slot_id'), 'procurement_requests', ['confirmed_slot_id'], unique=False)
    op.create_foreign_key('fk_procurement_requests_confirmed_centre_id', 'procurement_requests', 'procurement_centres', ['confirmed_centre_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_procurement_requests_confirmed_slot_id', 'procurement_requests', 'centre_slots', ['confirmed_slot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_procurement_requests_confirmed_slot_id', 'procurement_requests', type_='foreignkey')
    op.drop_constraint('fk_procurement_requests_confirmed_centre_id', 'procurement_requests', type_='foreignkey')
    op.drop_index(op.f('ix_procurement_requests_confirmed_slot_id'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_confirmed_centre_id'), table_name='procurement_requests')
    op.drop_column('procurement_requests', 'confirmed_slot_id')
    op.drop_column('procurement_requests', 'confirmed_centre_id')

    op.drop_index(op.f('ix_centre_slots_status'), table_name='centre_slots')
    op.drop_index(op.f('ix_centre_slots_slot_date'), table_name='centre_slots')
    op.drop_index(op.f('ix_centre_slots_centre_id'), table_name='centre_slots')
    op.drop_index(op.f('ix_centre_slots_capacity_id'), table_name='centre_slots')
    op.drop_table('centre_slots')
    # ### end Alembic commands ###
