"""create core domain tables

Revision ID: 7681cace46aa
Revises:
Create Date: 2026-09-17 15:47:47.453852+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7681cace46aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Authoritative commodity UUID'),
    sa.Column('commodity_code', sa.String(length=50), nullable=False, comment='Unique commodity code'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Commodity name'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Commodity active flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_commodity_code'), 'commodities', ['commodity_code'], unique=True)
    op.create_index(op.f('ix_commodities_is_active'), 'commodities', ['is_active'], unique=False)
    op.create_table('procurement_centres',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Authoritative procurement centre UUID'),
    sa.Column('centre_code', sa.String(length=50), nullable=False, comment='Unique procurement centre code'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Procurement centre name'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='Centre address'),
    sa.Column('district', sa.String(length=150), nullable=True, comment='District'),
    sa.Column('state', sa.String(length=150), nullable=True, comment='State'),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='Centre geographic location in WGS84'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Centre active flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_centres_centre_code'), 'procurement_centres', ['centre_code'], unique=True)
    op.create_index(op.f('ix_procurement_centres_district'), 'procurement_centres', ['district'], unique=False)
    op.create_index(op.f('ix_procurement_centres_is_active'), 'procurement_centres', ['is_active'], unique=False)
    op.create_index(op.f('ix_procurement_centres_state'), 'procurement_centres', ['state'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Authoritative user UUID'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Primary login phone number for OTP authentication'),
    sa.Column('role', sa.String(length=32), nullable=False, comment='User role (FARMER, CENTRE_OPERATOR, GOVERNMENT)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active account flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Authoritative farmer profile UUID'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Linked user account UUID'),
    sa.Column('full_name', sa.String(length=150), nullable=False, comment='Farmer name'),
    sa.Column('village', sa.String(length=150), nullable=True, comment='Village/locality'),
    sa.Column('district', sa.String(length=150), nullable=True, comment='District'),
    sa.Column('state', sa.String(length=150), nullable=True, comment='State'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active farmer profile flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_district'), 'farmers', ['district'], unique=False)
    op.create_index(op.f('ix_farmers_is_active'), 'farmers', ['is_active'], unique=False)
    op.create_index(op.f('ix_farmers_user_id'), 'farmers', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmers_user_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_is_active'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_district'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_procurement_centres_state'), table_name='procurement_centres')
    op.drop_index(op.f('ix_procurement_centres_is_active'), table_name='procurement_centres')
    op.drop_index(op.f('ix_procurement_centres_district'), table_name='procurement_centres')
    op.drop_index(op.f('ix_procurement_centres_centre_code'), table_name='procurement_centres')
    op.drop_table('procurement_centres')
    op.drop_index(op.f('ix_commodities_is_active'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_commodity_code'), table_name='commodities')
    op.drop_table('commodities')
    # ### end Alembic commands ###
