"""add procurement requests

Revision ID: 4f4f7a08c9a9
Revises: 40c0e5df6d85
Create Date: 2026-09-17 17:42:42.155176+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4f4f7a08c9a9'
down_revision: Union[str, None] = '40c0e5df6d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_requests',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Authoritative procurement request UUID'),
    sa.Column('farmer_id', sa.Uuid(), nullable=False, comment='Farmer submitting the procurement request'),
    sa.Column('commodity_id', sa.Uuid(), nullable=False, comment='Requested commodity'),
    sa.Column('requested_quantity', sa.Numeric(precision=12, scale=3), nullable=False, comment='Requested quantity in quintals'),
    sa.Column('preferred_date', sa.Date(), nullable=False, comment="Farmer's preferred procurement date"),
    sa.Column('farmer_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='Request-time farmer location in WGS84'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Current procurement request workflow status'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Request creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Request last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_requests_commodity_id'), 'procurement_requests', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_procurement_requests_farmer_id'), 'procurement_requests', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_procurement_requests_preferred_date'), 'procurement_requests', ['preferred_date'], unique=False)
    op.create_index(op.f('ix_procurement_requests_status'), 'procurement_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_requests_status'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_preferred_date'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_farmer_id'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_commodity_id'), table_name='procurement_requests')
    op.drop_table('procurement_requests')
    # ### end Alembic commands ###
