"""add centre capacity

Revision ID: 40c0e5df6d85
Revises: edec4a58fc2f
Create Date: 2026-09-17 16:26:32.263438+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c0e5df6d85'
down_revision: Union[str, None] = 'edec4a58fc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centre_capacity',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Authoritative centre-capacity UUID'),
    sa.Column('centre_id', sa.Uuid(), nullable=False, comment='Procurement centre UUID'),
    sa.Column('capacity_date', sa.Date(), nullable=False, comment='Date for which this capacity applies'),
    sa.Column('daily_quantity_capacity', sa.Numeric(precision=12, scale=3), nullable=False, comment='Maximum planned procurement quantity in quintals'),
    sa.Column('committed_quantity', sa.Numeric(precision=12, scale=3), nullable=False, comment='Quantity already committed for this centre and date in quintals'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this capacity configuration is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['procurement_centres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('centre_id', 'capacity_date', name='uq_centre_capacity_date')
    )
    op.create_index(op.f('ix_centre_capacity_capacity_date'), 'centre_capacity', ['capacity_date'], unique=False)
    op.create_index(op.f('ix_centre_capacity_centre_id'), 'centre_capacity', ['centre_id'], unique=False)
    op.create_index(op.f('ix_centre_capacity_is_active'), 'centre_capacity', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_centre_capacity_is_active'), table_name='centre_capacity')
    op.drop_index(op.f('ix_centre_capacity_centre_id'), table_name='centre_capacity')
    op.drop_index(op.f('ix_centre_capacity_capacity_date'), table_name='centre_capacity')
    op.drop_table('centre_capacity')
    # ### end Alembic commands ###
