"""add centre commodity capability

Revision ID: edec4a58fc2f
Revises: 7681cace46aa
Create Date: 2026-09-17 16:12:00.432769+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edec4a58fc2f'
down_revision: Union[str, None] = '7681cace46aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centre_commodities',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Authoritative centre-commodity UUID'),
    sa.Column('centre_id', sa.Uuid(), nullable=False, comment='Procurement centre UUID'),
    sa.Column('commodity_id', sa.Uuid(), nullable=False, comment='Supported commodity UUID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this centre currently accepts the commodity'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['procurement_centres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('centre_id', 'commodity_id', name='uq_centre_commodity')
    )
    op.create_index(op.f('ix_centre_commodities_centre_id'), 'centre_commodities', ['centre_id'], unique=False)
    op.create_index(op.f('ix_centre_commodities_commodity_id'), 'centre_commodities', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_centre_commodities_is_active'), 'centre_commodities', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_centre_commodities_is_active'), table_name='centre_commodities')
    op.drop_index(op.f('ix_centre_commodities_commodity_id'), table_name='centre_commodities')
    op.drop_index(op.f('ix_centre_commodities_centre_id'), table_name='centre_commodities')
    op.drop_table('centre_commodities')
    # ### end Alembic commands ###
